# Generated by Django 5.1.6 on 2025-03-17 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes_comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='dislike_count',
        ),
    ]
