# Generated by Django 5.1.6 on 2025-03-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes_comments', '0003_like_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
